# Correct Security Group with Inbound 8080 and ALL Outbound
  ContainerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security Group for Merck DevOps API
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1 # Allow all outbound to pull image
          CidrIp: 0.0.0.0/0

  # Service configured for FARGATE
ECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref TaskDefinition
      LaunchType: FARGATE # THIS IS THE CRITICAL FIX
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-xxxxxx # Must be a Public Subnet ID
          SecurityGroups:
            - !Ref ContainerSecurityGroup